version: "3"

services:
  db:
    container_name: db
    build:
      context: ./db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - ./db/sql_script:/sql_script

  gateway:
    container_name: gateway
    build:
      context: ./gateway
    ports:
      - 80:80
    expose:
      - '80'
    restart: always
    volumes:
      - ./gateway/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - apiserver
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  api:
    container_name: api
    build:
      context: ./api
    ports:
      - 8001:8000
    environment:
      NODE_ENV: "product"
      DB_ID: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: ${DB_NAME}"
      DB_HOST: 'db'
    volumes:
      - ./api/app:/app
    command: '/bin/sh -c "npm install && npm start"'
